import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { DbRouter, migrateControlDb } from '../../db/router.js'
import { apiRoutes } from '../api.js'

/**
 * ルート台帳（issue #114 の分割の安全網）。
 *
 * api.ts をドメイン別サブルーターへ分割しても「公開しているルートの集合」が
 * 変わらないことを機械検証する。分割の各コミットはこのテストが green のまま進める。
 * ルートを意図して増減させたときだけ、この一覧を更新する（差分がレビューに見える）。
 */

let tmp: string
beforeEach(() => {
  tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'kanean-routes-'))
  process.env.DATA_DIR = tmp
  migrateControlDb()
})
afterEach(() => fs.rmSync(tmp, { recursive: true, force: true }))

const ROUTES = [
  'DELETE /attachments/:id',
  'DELETE /entries/:id',
  'DELETE /filing/records/:id',
  'DELETE /opening-balances/:id',
  'DELETE /proration-settings/:id',
  'DELETE /rules/:id',
  'DELETE /tags/:id',
  'GET /accounts',
  'GET /attachments/:id/download',
  'GET /audit-logs',
  'GET /business-settings',
  'GET /closing/capital-transfer/preview',
  'GET /closing/rollover/precheck',
  'GET /counterparties',
  'GET /departments',
  'GET /documents',
  'GET /documents/:id',
  'GET /drafts',
  'GET /entries',
  'GET /entries/:id',
  'GET /entries/:id/attachments',
  'GET /filing/instruction-sheet',
  'GET /filing/precheck',
  'GET /filing/records',
  'GET /fiscal-years',
  'GET /fiscal-years/suggested',
  'GET /fixed-assets',
  'GET /fixed-assets/:id/schedule',
  'GET /fixed-assets/used-useful-life',
  'GET /import-accounts',
  'GET /import-formats',
  'GET /items',
  'GET /opening-balances',
  'GET /proration-settings',
  'GET /raw-transactions',
  'GET /reports/blue-statement',
  'GET /reports/breakdown/depreciation',
  'GET /reports/breakdown/monthly-sales-purchase',
  'GET /reports/breakdown/rent',
  'GET /reports/breakdown/salary',
  'GET /reports/breakdown/senju',
  'GET /reports/bs',
  'GET /reports/bs.csv',
  'GET /reports/comparison/bs',
  'GET /reports/comparison/bs.csv',
  'GET /reports/comparison/pl',
  'GET /reports/comparison/pl.csv',
  'GET /reports/comparison/trial-balance',
  'GET /reports/comparison/trial-balance.csv',
  'GET /reports/department-pl',
  'GET /reports/department-pl.csv',
  'GET /reports/department-trial-balance',
  'GET /reports/department-trial-balance.csv',
  'GET /reports/journal.csv',
  'GET /reports/ledger/:accountId',
  'GET /reports/ledger/:accountId/csv',
  'GET /reports/monthly-trend',
  'GET /reports/monthly-trend.csv',
  'GET /reports/pl',
  'GET /reports/pl.csv',
  'GET /reports/reconciliation',
  'GET /reports/sub-ledger/:subAccountId',
  'GET /reports/sub-ledger/:subAccountId/csv',
  'GET /reports/tax-excluded-pl',
  'GET /reports/tax-excluded-pl.csv',
  'GET /reports/tax-sales',
  'GET /reports/tax-sales.csv',
  'GET /reports/trial-balance',
  'GET /reports/trial-balance.csv',
  'GET /rules',
  'GET /services',
  'GET /services/catalog',
  'GET /settlement/links',
  'GET /settlement/transfer-candidates',
  'GET /sub-accounts',
  'GET /tags',
  'GET /tax-categories',
  'GET /tax-return/blue-deduction',
  'GET /tax-return/blue-statement',
  'GET /tax-return/blue-statement-official.pdf',
  'GET /tax-return/blue-statement.pdf',
  'GET /tax-return/consumption',
  'GET /tax-return/consumption-official.pdf',
  'GET /tax-return/consumption.pdf',
  'GET /tax-return/income-tax',
  'GET /tax-return/income-tax-official.pdf',
  'GET /tax-return/income-tax.pdf',
  'PATCH /import-formats/:id',
  'PATCH /lines/:lineId',
  'POST /closing/reopen/:id',
  'POST /closing/rollover',
  'POST /counterparties',
  'POST /counterparties/:id/active',
  'POST /departments',
  'POST /departments/:id/active',
  'POST /documents',
  'POST /documents/:id/collect',
  'POST /documents/:id/issue',
  'POST /documents/:id/receipt',
  'POST /documents/:id/void',
  'POST /entries',
  'POST /entries/:id/attachments',
  'POST /entries/:id/confirm',
  'POST /entries/:id/unconfirm',
  'POST /entries/confirm-batch',
  'POST /filing/records',
  'POST /filing/records/:id/attachments',
  'POST /fiscal-years',
  'POST /fixed-assets',
  'POST /fixed-assets/:id/retire',
  'POST /fixed-assets/:id/sell',
  'POST /fixed-assets/post-depreciation',
  'POST /import',
  'POST /import-accounts',
  'POST /import-formats',
  'POST /items',
  'POST /items/:id/active',
  'POST /opening-balances',
  'POST /proration-settings',
  'POST /proration/post',
  'POST /raw-transactions/:id/ignore',
  'POST /raw-transactions/:id/restore',
  'POST /rules',
  'POST /rules/:id/active',
  'POST /services',
  'POST /settlement/link',
  'POST /settlement/unlink',
  'POST /sub-accounts',
  'POST /sub-accounts/:id/active',
  'POST /sub-accounts/by-counterparty',
  'POST /tags',
  'POST /tax-return/blue-deduction/settings',
  'POST /tax-return/income-tax/inputs',
  'POST /tax-return/withholding-sale',
  'PUT /business-settings',
  'PUT /counterparties/:id',
  'PUT /departments/:id',
  'PUT /documents/:id',
  'PUT /entries/:id',
  'PUT /items/:id',
  'PUT /rules/:id',
  'PUT /sub-accounts/:id',
] as const

describe('api ルート台帳', () => {
  it('method+path の集合が台帳と一致する（143本）', () => {
    const app = apiRoutes(new DbRouter())
    const actual = [...new Set(app.routes.filter((r) => r.method !== 'ALL').map((r) => `${r.method} ${r.path}`))].sort()
    expect(actual).toEqual([...ROUTES])
  })
})
